pokemon images
avalon-js-bootcamp/pokemon-discover pull request #4
Opened 2023-06-01 07:48 UTC by xBunnicornx

background + images + banner + shadow

2023-06-02 00:32 UTC, roman-yakobnyuk commented
@xBunnicornx looks like your build has failed, please check it locally.

2023-06-09 01:48 UTC, roman-yakobnyuk requested changes

2023-06-09 01:48 UTC, roman-yakobnyuk commented on src/app/page.tsx
>            alt="Next.js Logo"
Please replace this with correct alternative text.

2023-06-09 01:48 UTC, roman-yakobnyuk commented on src/app/styles/page.css
> +  right: -245px;
There is some weird CSS here, I do not really understand it.

2023-06-09 01:48 UTC, roman-yakobnyuk commented on src/app/styles/page.css
> +.tittle {
There is a typo here.

2023-06-09 01:48 UTC, roman-yakobnyuk commented on src/app/styles/page.css
> +@media only screen and (max-width: 480px) {
Please make sure to leave an empty line between blocks.

2023-06-15 02:14 UTC, xBunnicornx commented on src/app/page.tsx
> +          <button><img  width="20" height="20" src="https://img.icons8.com/ios/50/running--v1.png" alt="running--v1"/>  Run Away</button>
yeah i fixed it.

2023-06-15 02:14 UTC, xBunnicornx commented on src/app/styles/page.css
> +  clip-path: polygon(45px 0, 100% 0, 100% 100%, 0 100%);
this is for the banner.

2023-06-15 02:15 UTC, xBunnicornx commented on src/app/styles/page.css
> +  -moz-transform: scaleX(-1);
cause the run icon. it face opposite site. so i tried to flip it

2023-07-06 05:51 UTC, merged